### ISSUE TITLE
Ship name as per station control

### ISSUE THREAD

**Issue by sabreqld** [cmdrmcdonald/EliteDangerousDataProvider#120]
more a quick question, than an issue.
Is there a variable that states the ship name as per game?

EDDI responds to the station on supercruise exit, but I cannot find it in the EDDI variables list.

EG:  Faulcon Delacy Sierra Alpha Bravo - as opposed to the name set in the EDDI parameters?

**Comment by Darkcyde13** [comment]
Use this:
`{ShipCallsign()}`
It will do what you are asking for.  It's listed in the help file.

You can also provide ship details if you wish one of your other ships to be said instead of the current one.  Interestingly, if you provide an ID number, every ship you have ever owned is remembered by the game. For example:
`{ShipCallsign(1)}`
will report the callsign of your very first ship that you started the game with.

**Comment by sabreqld** [comment]
Ah, i was looking for it for voice attack and only found this:
{TXT:Ship callsign}: the callsign of the ship as shown in EDDI configuration (e.g. "GEF-1020")
which pointed to the EDDI shipyard variable.

I shall try this out :)

**Comment by sabreqld** [comment]
This absolutely works, you are brilliant.
