### ISSUE TITLE
Delay firing of ((EDDI commander continued)) and/or ((EDDI commander progress))

### ISSUE THREAD

**Issue by omega9380** [cmdrmcdonald/EliteDangerousDataProvider#157]
The progress and continued actions seem to fire almost simultaneously.  I am assuming continued should fire first, then progress.  My VA profile has actions for both triggers, but what sometimes happens is they fire over top of the one another, resulting in some odd output.  I have tried setting the continued action to prevent other actions until done, but sometimes this means progress never fires.  Could you introduce a small delay to the progress action, or some way of the continued action to report back and tell the progress action to go ahead and fire?  I usually use EDDI and VA strictly to populate a running text log, as opposed to having EDDI talking to me, so I haven't noticed if progress and continued are trying to fire over top one another for the voice responder.  A minor annoyance in an otherwise awesome program.  Thanks!!

**Comment by cmdrmcdonald** [comment]
EDDI fires responders for each event as they occur.  This is by design, to avoid issues with long-running responders (e.g. long speeches) blocking other events from triggering.

I don't know if VoiceAttack honours the 'allow other commands to be executed while this one is running' flag for commands fired by plugins, but it should, so worth trying that out and if it doesn't work to raise it as an issue on the VoiceAttack forums.
