### ISSUE TITLE
Enhancement - Add current EDDI version to profile data returned by EDDI

### ISSUE THREAD

**Issue by MarkAusten** [cmdrmcdonald/EliteDangerousDataProvider#19]
Add a new EDDI call (EDDI current version?) that returns the current version of EDDI. This should replace the hard-coded string in the EDDI: Startup command. Thus:

Execute external plugin, 'EDDI 1.2.1' and wait for return (context is profile, text variables is EDDI ship script)
Set Text [EDDI latest version] to [http://api.eddp.co/eddi/version]
Begin Text Compare: [EDDI latest version] does not equal [TXT:EDDI current version]
and so on...

**Comment by cmdrmcdonald** [comment]
It's a nice idea but hits problems due to VoiceAttack's architecture.

Plugins in VoiceAttack are initialised asynchronously, so there is no way of knowing when the plugin's initialisation has finished and the variables are available.  The EDDI startup command is run as soon as VoiceAttack starts (well, as soon as the profile is loaded which is usually very close to the same thing) so you're in a race condition between the startup command the the plugin initialisation.  I played around with some options to mitigate this in an earlier version of the profile scripts but just hardcoding the version in the script ended up being the simplest solution.
