### ISSUE TITLE
Some data concerning the ship varaiables are set to zero

### ISSUE THREAD

**Issue by Pryss** [cmdrmcdonald/EliteDangerousDataProvider#192]
Not tested all of them, but the following datas are set to zero : 
{DEC:Ship total fuel tank capacity}
{DEC:Ship fuel tank capacity}

There are also the ship variables soncerning the cargo wich are zeroed.

I'm using EDDI with voice attack.

**Comment by Darkcyde13** [comment]
This is a known issue.  FDev made some changes that mean these variables are now obtained a different way.  Cmdr. McDonald posted the following in issue #179:-

"Apologies for the delay in providing a fix for this, I will address this issue today. Please note that this due to undocumented changes in the Frontier API the following features will no longer be available:
engineer modifications when exporting to Coriolis
ability to export stored ships to Coriolis
information about the total and current amounts of fuel
information about the total and current amounts of cargo
Some of these items can be obtained in a different way to that how they are obtained today, and will be reinstated in a future patch."

**Comment by sabreqld** [comment]
Noticed this myself, glad to know it wasn't just me.
My exploration ship keeps reporting 'not set % fuel remaining' because it can't divide by zero :D

**Comment by cmdrmcdonald** [comment]
This data is back, as far as possible, in 2.3 beta 2.
