### ISSUE TITLE
Beta bug: Shipyard ship names

### ISSUE THREAD

**Issue by Tkael** [cmdrmcdonald/EliteDangerousDataProvider#205]
1. Spaces are removed from the ship names in the shipyard.
2. IPA phonetic pronunciations do not seem to override the default pronunciation.

**Comment by Tkael** [comment]
Example: my ship is named "The Windblown Leaf"
The shipyard registers the name as "thewind****nleaf"
Pronunciation is butchered.

**Comment by cmdrmcdonald** [comment]
Please could you send me your journal for the time at which you named your ship so that I can see what information is provided to EDDI from Elite?

Regarding the IPA pronunciation, what is the situation in which you are hearing the ship name, and can you confirm that you have phonetic speech enabled in the EDDI's text to speech tab?

**Comment by Tkael** [comment]
Here you go. Oddly, the journal seems to have it right even though the shipyard has it wrong.

{ "timestamp":"2017-04-19T04:53:38Z", "event":"SetUserShipName", "Ship":"asp", "ShipID":6, "UserShipName":"the windblown leaf", "UserShipId":"TK-19A" }

[Journal.170418195557.01.zip](https://github.com/cmdrmcdonald/EliteDangerousDataProvider/files/950472/Journal.170418195557.01.zip)

[Shipyard.zip](https://github.com/cmdrmcdonald/EliteDangerousDataProvider/files/950476/Shipyard.zip)

Note also that the Imperial Courier and Imperial Clipper are being rendered as 'Empire_Courier' & 'Empire_Trader' respectively.

**Comment by cmdrmcdonald** [comment]
The shipyard looks corrupted to me.  Please could you shut down EDDI, remove the %APPDATA%\shipmonitor.json file, and restart EDDI?  You'll need to swap in to your ships for EDDI to pick up the data but after that it should behave.

It's possible that the corruption is due to multiple attempts to update the ship data at the same time, so I've altered the code to lock the shipyard prior to updating it.  I'll make a beta 4 release, hopefully later today, which should fix the problem permanently.

**Comment by cmdrmcdonald** [comment]
Beta 4 of EDDI has just been released which should avoid this issue.  It avoid using any names that might have been filtered when updating local ship information, in addition to the shipyard locking that should remove corruption issues.  Please let me know if you encounter this issue again.

**Comment by Tkael** [comment]
Confirmed as fixed. An additional observation of beta 4/5 behavior:
Switching to and from "the Windblown Leaf" did not update the name in the shipyard, though renaming the ship in livery did update the shipyard.
