### ISSUE TITLE
EDDI stopped reading incoming messages

### ISSUE THREAD

**Issue by TalShaf** [cmdrmcdonald/EliteDangerousDataProvider#271]
I have restored the script to default and it still doesn't work. It works only when I remove the following: 

```
{if event.player = true:
    {if event.message = "o7":
        {event.from} salutes
        {if event.channel = "player":
            you
        }.
    |else:
```

Otherwise it's completely silent.

**Comment by Darkcyde13** [comment]
That part you have removed, makes it so only messages from other human players are read out aloud.  If you play in Solo or Group, this is why you would hear nothing.  This is why removing it will make you hear everything.

That part is useful so that EDDI is not reading out messages all the time when you at docked at a station.  This will get annoying very quickly.

**Comment by TalShaf** [comment]
Ah, I misunderstood, I thought it was only for player salute messages. Thanks for the clarification. Closing this issue.
