### ISSUE TITLE
Support for translations?

### ISSUE THREAD

**Issue by DanielGSan** [cmdrmcdonald/EliteDangerousDataProvider#45]
Hi!
First of all, congrats for a great program.
I want to ask if there are some plan to add a feature for easily translate to other languages.

Probably is not needed, because you can create your own scripts with your own responses, but at least the program language.

What do you think?

Thanks in advance

**Comment by cmdrmcdonald** [comment]
I didn't build EDDI with translations in mind, mainly because it started out being a pure VoiceAttack plugin and so didn't have any external UI.  Now that it has one some localisation would be nice, but I don't have the time to add localisation ability in any time soon.  Pull requests are always welcome!

**Comment by DanielGSan** [comment]
Ok, no problem, is more a secondary feature, probably I can help in the future, but now I'm really busy in my work.

Thanks for the answer.
