### ISSUE TITLE
Station commodities not always being loaded

### ISSUE THREAD

**Issue by TROG111** [cmdrmcdonald/EliteDangerousDataProvider#63]
I have found that frequently the station.commodities list is not being populated when I arrive at a new station (.g. Dock).  I hve reviewed the log file and the data is being returned by the appropriate companion/EDDN service.  However, when Iask EDDI to report on the number of commodities available at this station it frequently says 0.

I will try to create a logfile that demonstrates this (and does not have other irrelevant stuff).

**Comment by TROG111** [comment]
Here is the EDDI log extract for my most recent docking.  As you can see, the station data is return correctly, however when I call len(thisstation.commodities) it returns 0
[eddi-1.log.txt](https://github.com/cmdrmcdonald/EliteDangerousDataProvider/files/609346/eddi-1.log.txt)

**Comment by cmdrmcdonald** [comment]
Sometimes the companion API runs slowly, as in the log you provided where you can see that the station the commodities is returned for is not the station at which you docked.  Although EDDI could in theory keep poking the companion API until it receives the correct result this would add a significant amount of complexity due to the various combinations of player and API states, and is not something I'm planning on tackling inside EDDI.
