### ISSUE TITLE
FEature Request: new system discovered

### ISSUE THREAD

**Issue by andreaspada** [cmdrmcdonald/EliteDangerousDataProvider#69]
Hi! Don't know if this is possible with the current implementation, but I would love to have a respond that notify me when I enter a system which is not already recorded in EDSM. Can this be done currently? If so, can someone tell me how or point me to the right direction?

**Comment by cmdrmcdonald** [comment]
EDDI does not obtain information from EDSM, however it does obtain data from EDDB.  You could check for the presence of {system.EDDBID} and if it isn't there then there's a fair chance that the data isn't in EDDB.

I say fair chance, because there is a delay between data being submitted to EDDN, it arriving in EDDB, EDDB dumping the data to a file, and EDDI picking that file up.  So you can guarantee that if {system.EDDBID} is present then the data is definitely in EDDB, but if {system.EDDBID} is not present you can only safely assume that the data wasn't in EDDB a few days ago.
