### ISSUE TITLE
SystemDetails not populating correctly? Beta 2.1

### ISSUE THREAD

**Issue by TROG111** [cmdrmcdonald/EliteDangerousDataProvider#72]
Im having trouble with the following script which I have added added to the 'Entered normal space' script.  As you can see I want to warn if the gravity of the planet is 'high', but I dont seem to be able to get hold of the body object.

{if event.bodytype = 'Planet':
    {OneOf("near", "close to", "in the vicinity of")} planet {P(event.body)}
    {set currentsystem to SystemDetails(event.system)}
{currentsystem.name} has {len(currentsystem.bodies)} bodies
    {for body in currentsystem.bodies:
{body.name}
        {if body.name = event.body
            {if body.gravity > 0.5:
                Alert! {OneOf("this planets", P(event.name), "region")} has a significant gravitational pull.
            |elif body.gravity > 0.25:
                Warning! medium gravitation pull in this location.
            }
        }
    }
{F("Prospect planet")}
|elif event.bodytype = 'Star':
    {OneOf("near", "close to", "in the vicinity of")} star {P(event.body)}
  |elif event.bodytype = 'Station':
    {OneOf("near", "close to", "in the vicinity of")} {P(event.body)}
}.

The following is a transcript of the output

 Haul a con-da has returned to normal space near planet Hudson Brooks Samkyha has 0 bodies Analysing planets rare material composition... please stand by....

**Comment by TROG111** [comment]
Ok, now it seems to be working?

**Comment by cmdrmcdonald** [comment]
System details relies on EDDB for information.  If EDDB doesn't have the data then it won't show up in EDDI.

In the example of Samkyha EDDB has no information on bodes, as can be seen at https://eddb.io/system/bodies/16452

Unfortunately there is nothing to allow us to discern whether there are actually no bodies, or just no bodies because no-one has entered the data yet.  In the case of unknown bodies a planetary scan with a DSS will add the data to EDDB (eventually), but in the case of already-known bodies the only thing that can be done is manual entry.

**Comment by TROG111** [comment]
OK, that makes sense!  I can check whether the EDDB data is up to date since I know that I am at a planet (event.body), therefore, if SystemDetails does not identify the body it must be because EDDB doesnt have it.
