### ISSUE TITLE
Speech response doesn’t always use correct voice.

### ISSUE THREAD

**Issue by knocks-** [cmdrmcdonald/EliteDangerousDataProvider#88]
I purchased a Cereproc voice (Jess) for use with EEDI, many responses such as (system report, Body scanned, Entered supercruise) will use the default Microsoft voice instead of the Cereproc voice. 

I’m using windows 10 and EDDI 2.0.13

**Comment by knocks-** [comment]
Cereproc voice is poor quality, issue not present after testing with an Ivona voice.

**Comment by rhodium88** [comment]
I know this is a bit late, but I was having this issue and I found a solution. There is a registry value that needed to be changed for the Cereproc voice to be used for all responses in EDDI.

The registry key to change is in HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\SPEECH\Voices\Tokens\CereVoice Caitlin 4.0.4\Attributes

The "Language" key was set to 409;809 (these are the MS language codes for English US and English UK respectively.)
I set this to 809;409 (so that English UK preceded English US)
and after restarting Voice Attack, all responses were working with the Cereproc voice!

The issue seems to have been with the Pause function not working when English US was listed first in the language codes.

The Jess voice is rather good (I'm also a fan of Caitlin) so I hope this helps anyone trying to get it to work with EDDI.
